[package]
name = "stpsyr"
description = "a Diplomacy adjudicator in Rust"
version = "0.1.0"
authors = ["KeyboardFire <andy@keyboardfire.com>"]
license = "GPL-3.0"

[dependencies]
csv = "1.3.1"
bincode = "1.3.3"
serde = "1.0.11"
serde_derive = "1.0.11"
regex = "1.11.1"
